Add friends likes
DanielSJavaDev/java-filmorate pull request #2
Opened 2022-10-09 11:54 UTC by DanielSJavaDev

2022-10-10 17:21 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохо - но надо еще поработать над рефакторингом.

2022-10-11 18:04 UTC, krylov-sergey-sergeevich approved these changes
Привет, в целом хорошо. Добавил 1 комментарий который просьба учесть перед следующей работой, из-за него на переделку отправлять обидно, но он тоже достаточно важен.

2022-10-11 18:04 UTC, krylov-sergey-sergeevich commented on src/main/java/filmorate/service/UserService.java
> +        userStorage.getUsersData().get(userId).getFriends().add(friendId);
userStorage.getUsersData().get(userId).getFriends().add(friendId);

в этом и других случаях я имел виду сделать, что-то подобное
userStorage.getUsersData().get(userId).addFriend(friendId); - те мы пишем метод который сам внутри как-то добавляет/удаляем, мне как внешнему разработчику абсолютно не известна логика/правила по которым мы имеем право добавить друга, поэтому я жду у пользователя такой метод. В других случаях аналогично.

2022-10-13 10:02 UTC, DanielSJavaDev commented on src/main/java/filmorate/service/UserService.java
> +        userStorage.getUsersData().get(userId).getFriends().add(friendId);
Теперь понял о чём речь, исправлю в следующей работе, спасибо за ревью! :)

2022-10-13 10:03 UTC, merged