Add database
DanielSJavaDev/java-filmorate pull request #6
Opened 2022-11-16 00:57 UTC by DanielSJavaDev

Привет, ревьюер. Очень не хочу в академ, поэтому сдаю работу пока без доделанных тестов. Пока работа будет проверяться, надеюсь успеть всё привести в порядок, с нетерпением жду комментариев :)

2022-11-16 06:04 UTC, krylov-sergey-sergeevich requested changes
Привет

- Почему файл с постманом удален?
- На нашел диаграммы
- Еще момент, я точно не нашел где в коде происходит данный кейс(во 2 проверке еще поищу), немного логика переплетена, но нужно учитывать что _"чтоб при получении всех фильмов, жанры были получены в одном запросе, в не выполнены вв цикле перебором по фильмам"_

2022-11-16 14:22 UTC, DanielSJavaDev commented on src/main/java/filmorate/FilmorateApplication.java
> +/*trrrr*/
Крик души :D

2022-11-16 14:27 UTC, DanielSJavaDev commented on src/main/java/filmorate/controller/UserController.java
> +    public Collection<User> get() {
Воевал с посманом, пробовал все подряд коллекции, поэтому так, сейчас исправлю

2022-11-16 18:20 UTC, DanielSJavaDev commented
И снова здравствуйте, постман файл удалил старый, добавил новый.
Диаграмму добавил.
Все тесты поправил, всё проходит, ничего не падает.
По замечаниям всё поправил.

2022-11-17 05:10 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2022-11-17 11:24 UTC, merged